apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-controller
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://hiremeup.online"
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
    - host: hiremeup.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hiremeupfrontend-service
                port:
                  number: 5173
          - path: /api/v1/chat
            pathType: Prefix
            backend:
              service:
                name: hiremeup-chat-service
                port:
                  number: 4003
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: hiremeup-chat-service
                port:
                  number: 4003
          - path:  /api/v1/auth
            pathType: Prefix
            backend:
              service:
                name: hiremeup-auth-service
                port:
                  number: 4001
          - path:  /api/v1/company
            pathType: Prefix
            backend:
              service:
                name: hiremeup-company-service
                port:
                  number: 4006
          - path: /api/v1/job
            pathType: Prefix
            backend:
              service:
                name: hiremeup-job-service
                port:
                  number: 4005
          - path: /api/v1/notification
            pathType: Prefix
            backend:
              service:
                name: hiremeup-notification-service
                port:
                  number: 4004
          - path: /api/v1/subscription
            pathType: Prefix
            backend:
              service:
                name: hiremeup-subscription-service
                port:
                  number: 4007
          - path: /api/v1/user
            pathType: Prefix
            backend:
              service:
                name: hiremeup-user-service
                port:
                  number: 4002
          - path: /api/v1/user/company
            pathType: Prefix
            backend:
              service:
                name: hiremeup-user-service
                port:
                  number: 4002
