apiVersion: apps/v1
kind: Deployment
metadata:
  name: hiremeup-company-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hiremeup-company-service
  template:
    metadata:
      labels:
        app: hiremeup-company-service
    spec:
      containers:
      - name: hiremeup-company-service
        image: shihadb/hiremeup-company-service:latest
        envFrom:
        - configMapRef:
            name: company-config 
---
apiVersion: v1
kind: Service
metadata:
  name: hiremeup-company-service
spec:
  selector:
    app: hiremeup-company-service
  ports:
  - protocol: TCP
    port: 4006
    targetPort: 4006