apiVersion: apps/v1
kind: Deployment
metadata:
  name: hiremeup-notification-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hiremeup-notification-service
  template:
    metadata:
      labels:
        app: hiremeup-notification-service
    spec:
      containers:
      - name: hiremeup-notification-service
        image: shihadb/hiremeup-notification-service:latest
        ports:
        - containerPort: 4004
        envFrom:
        - configMapRef:
            name: notification-config 
---
apiVersion: v1
kind: Service
metadata:
  name: hiremeup-notification-service
spec:
  selector:
    app: hiremeup-notification-service
  ports:
  - protocol: TCP
    port: 4004
    targetPort: 4004
